- name: update cache repo
  apt:
    update_cache: yes

- name: install nginx
  apt:
    name: nginx    

- name: copy files website
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
  with_fileglob:
    - "files/html/*"